# Generated by Django 6.1.1 on 2026-09-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
