# Generated by Django 6.1.1 on 2026-09-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('plazo', models.DateField()),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='eventos.evento')),
            ],
        ),
    ]
