# Generated by Django 6.1.1 on 2026-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_subtarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
