# Generated by Django 6.1.1 on 2026-10-08 18:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_configuracionorganizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionorganizador',
            name='limite_horas_diarias',
            field=models.DecimalField(decimal_places=2, default=Decimal('6'), max_digits=4, validators=[django.core.validators.MinValueValidator(1, 'El límite debe estar entre 1 y 16 horas.'), django.core.validators.MaxValueValidator(16, 'El límite debe estar entre 1 y 16 horas.')]),
        ),
    ]
